# This file contains the constants which is used in the project

NUM_ROWS = 20
NUM_COLS = 20
INF = 1e9

X = [1, 0, -1, 0]
Y = [0, 1, 0, -1]

STARTING_POSITION_OF_AGENT = (0, 0)

PROBABILITY_OF_GRID = 0.3
NUM_ITERATIONS = 100

FLAT_FALSE_NEGATIVE_RATE = 0.2
HILLY_FALSE_NEGATIVE_RATE = 0.5
FOREST_FALSE_NEGATIVE_RATE = 0.8
ZERO_PROBABILITY = 0.0
ONE_PROBABILITY = 1.0
