# This file contains the constants which is used in the project

NUM_ROWS = 50
NUM_COLS = 50
INF = 1e9

X = [1, 0, -1, 0]
Y = [0, 1, 0, -1]

# Change this path to other path where you want to store your images
IMG_PATH = "C:\\Users\\Gambit\\Documents\\Rutgers\\Rutgers 520\\Assignment 3\\Graphs"

STARTING_POSITION_OF_AGENT = (0, 0)

NUM_ITERATION_FOR_EACH_PROBABILITY = 50
#NUM_UNIFORM_SAMPLE_FOR_EACH_PROBABILITY = 34
#START_PROBABILITY = 0.0
#END_PROBABILITY = 0.33
PROBABILITY_OF_GRID = 0.3
#LIST_OF_PROBABILITIES = np.linspace(START_PROBABILITY, END_PROBABILITY, NUM_UNIFORM_SAMPLE_FOR_EACH_PROBABILITY)
HILLY_FALSE_NEGATIVE_RATE= (4,5)
FOREST_FALSE_NEGATIVE_RATE= (1,2)
FLAT_FALSE_NEGATIVE_RATE= (1,5)
ZERO_PROBABILITY = (0,1)
ONE_PROBABILITY = (1,1)

HILLY_FALSE_NEGATIVE_RATE= 0.5
FOREST_FALSE_NEGATIVE_RATE= 0.8
FLAT_FALSE_NEGATIVE_RATE= 0.2
ZERO_PROBABILITY = 0.0
ONE_PROBABILITY = 1.0


#TEMP_1 = [1,1]
#TEMP_2 = [1,1]
#TEMP_3 = [1,1]