# This file contains the constants which is used in the project

NUM_ROWS = 10
NUM_COLS = 10
INF = 1e9

X = [1, 0, -1, 0]
Y = [0, 1, 0, -1]

# Change this path to other path where you want to store your images
IMG_PATH = "C:\\Users\\Gambit\\Documents\\Rutgers\\Rutgers 520\\Assignment 3\\Graphs"

STARTING_POSITION_OF_AGENT = (0, 0)

NUM_ITERATION_FOR_EACH_PROBABILITY = 50
#NUM_UNIFORM_SAMPLE_FOR_EACH_PROBABILITY = 34
#START_PROBABILITY = 0.0
#END_PROBABILITY = 0.33
PROBABILITY_OF_GRID = 0.3
#LIST_OF_PROBABILITIES = np.linspace(START_PROBABILITY, END_PROBABILITY, NUM_UNIFORM_SAMPLE_FOR_EACH_PROBABILITY)
HILLY_FALSE_NEGATIVE_RATE= [8,10]
FOREST_FALSE_NEGATIVE_RATE= [5,10]
FLAT_FALSE_NEGATIVE_RATE= [2,10]